"""initial schema: queries, agent_outputs, final_decisions

Revision ID: 59a3b7d5ccb4
Revises: 
Create Date: 2026-07-24 23:49:25.645017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a3b7d5ccb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('fact_set', sa.JSON(), nullable=False),
    sa.Column('domain_profile', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_outputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('main_driver', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('extracted_facts', sa.JSON(), nullable=True),
    sa.Column('possible_explanations', sa.JSON(), nullable=True),
    sa.Column('ranked_hypotheses', sa.JSON(), nullable=True),
    sa.Column('acknowledged_weaknesses', sa.JSON(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('system_main_driver', sa.Text(), nullable=False),
    sa.Column('system_confidence_score', sa.Float(), nullable=False),
    sa.Column('signal_summary', sa.JSON(), nullable=True),
    sa.Column('net_bias', sa.String(length=32), nullable=True),
    sa.Column('decision_logic', sa.Text(), nullable=True),
    sa.Column('conflict_detected', sa.Boolean(), nullable=False),
    sa.Column('conflict_type', sa.String(length=32), nullable=True),
    sa.Column('conflicting_agents', sa.JSON(), nullable=True),
    sa.Column('dominant_narratives', sa.JSON(), nullable=True),
    sa.Column('contributing_agents', sa.JSON(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('final_decisions')
    op.drop_table('agent_outputs')
    op.drop_table('queries')
    # ### end Alembic commands ###
