"""add overconfident column to agent_outputs

Revision ID: 8e143e44f190
Revises: 8c0dc2a351c9
Create Date: 2026-07-25 04:13:16.019184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e143e44f190'
down_revision: Union[str, Sequence[str], None] = '8c0dc2a351c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_outputs', sa.Column('overconfident', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_outputs', 'overconfident')
    # ### end Alembic commands ###
